- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: cny
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'

- id: 600
  key: octacoin
  currency: oct
  sort_order: 3
  min_confirm: 1
  max_confirm: 6

- id: 800
  key: litecoin
  currency: ltc
  sort_order: 4
  min_confirm: 1
  max_confirm: 6

- id: 1000
  key: dogecoin
  currency: doge
  sort_order: 5
  min_confirm: 1
  max_confirm: 6

- id: 1200
  key: dashcoin
  currency: dsh
  sort_order: 6
  min_confirm: 1
  max_confirm: 6

#- id: 1400
#  key: ripple
#  currency: xrp
#  sort_order: 7
#  min_confirm: 1
#  max_confirm: 6

#- id: 1600
#  key: ethereum
#  currency: eth
#  sort_order: 8
#  min_confirm: 1
#  max_confirm: 6

#- id: 1800
#  key: bitsharesx
#  currency: bts
#  sort_order: 9
#  min_confirm: 1
#  max_confirm: 6

#- id: 2000
#  key: tether
#  currency: usdt
#  sort_order: 10
#  min_confirm: 1
#  max_confirm: 6

#- id: 2200
#  key: dash
#  currency: dash
#  sort_order: 11
#  min_confirm: 1
#  max_confirm: 6

#- id: 2400
#  key: trmb
#  currency: trmb
#  sort_order: 12
#  min_confirm: 1
#  max_confirm: 6

#- id: 2600
#  key: monero
#  currency: xmr
#  sort_order: 13
#  min_confirm: 1
#  max_confirm: 6

- id: 2800
  key: rubycoin
  currency: rby
  sort_order: 14
  min_confirm: 1
  max_confirm: 6

#- id: 3000
#  key: ybcoin
#  currency: ybc
#  sort_order: 15
#  min_confirm: 1
#  max_confirm: 6

#- id: 3200
#  key: primecoin
#  currency: xpm
#  sort_order: 16
#  min_confirm: 1
#  max_confirm: 6

- id: 3600
  key: gxcoin
  currency: gxc
  sort_order: 18
  min_confirm: 1
  max_confirm: 6

- id: 3800
  key: ggcoin
  currency: ggc
  sort_order: 19
  min_confirm: 1
  max_confirm: 6

- id: 40000
  key: oprcoin
  currency: opr
  sort_order: 20
  min_confirm: 1
  max_confirm: 6
