- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: cny
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelBank

- id: 600
  key: octacoin
  currency: oct
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelOctacoin

- id: 800
  key: litecoin
  currency: ltc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelLitecoin

- id: 1000
  key: dogecoin
  currency: doge
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelDogecoin

- id: 1200
  key: dashcoin
  currency: dsh
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelDashcoin

#- id: 1400
#  key: ripple
#  currency: xrp
#  fixed: 8
#  fee: 0.0005
#  inuse: true
#  type: WithdrawChannelRipple

#- id: 1600
#  key: ethereum
#  currency: eth
#  fixed: 8
#  fee: 0.0005
#  inuse: true
#  type: WithdrawChannelEthereum

#- id: 1800
#  key: bitsharesx
#  currency: bts
#  fixed: 8
#  fee: 0.0005
#  inuse: true
#  type: WithdrawChannelBitshares

#- id: 2000
#  key: tether
#  currency: usdt
#  fixed: 8
#  fee: 0.0005
#  inuse: true
#  type: WithdrawChannelTether

#- id: 2200
#  key: dash
#  currency: dash
#  fixed: 8
#  fee: 0.0005
#  inuse: true
#  type: WithdrawChannelDash

#- id: 2400
#  key: trmb
#  currency: trmb
#  fixed: 8
#  fee: 0.0005
#  inuse: true
#  type: WithdrawChannelTrmb

#- id: 2600
#  key: monero
#  currency: xmr
#  fixed: 8
#  fee: 0.0005
#  inuse: true
#  type: WithdrawChannelMonero

- id: 2800
  key: rubycoin
  currency: rby
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelRubycoin

#- id: 3000
#  key: ybcoin
#  currency: ybc
#  fixed: 8
#  fee: 0.0005
#  inuse: true
#  type: WithdrawChannelYBcoin

#- id: 3200
#  key: primecoin
#  currency: xpm
#  fixed: 8
#  fee: 0.0005
#  inuse: true
#  type: WithdrawChannelPrimecoin

- id: 3600
  key: gxcoin
  currency: gxc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelGxcoin

- id: 3800
  key: ggcoin
  currency: ggc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelGgcoin

- id: 4000
  key: oprcoin
  currency: opr
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelOprcoin
